[package]
name = "minify"
version = "0.0.1"
authors = ["castrogarciajs"]
license = "MIT"
description = "Rusty Fetcher is a CLI too"
repository = "https://github.com/castrogarciajs/rusty_fetcher"
edition = "2021"

[[bin]]
name = "fetchy"
path = "bin/main.rs"
doc = false

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
