[package]
name = "clippy"
version = "0.0.1"
authors = ["castrogarciajs"]
license = "MIT"
repository = "https://github.com/castrogarciajs/clippy"
edition = "2021"


[[bin]]
name = "clippy"
path = "bin/main.rs"

[[test]]
name = "test"
path = "test/main_test.rs"

[dependencies]
reqwest = "0.11.22"
clap = { version = "4.4.6", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }